temp/objects/Broker__c.object
<CustomObject>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Favorite__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Favorites</relationshipLabel>
        <relationshipName>Favorites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Favorite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/LeadAssociation__c.object
<CustomObject>
    <label>LeadAssociation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>LeadAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LeadAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Baths__c</fullName>
        <label>Baths</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beds__c</fullName>
        <label>Beds</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Listing</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>Under Contract</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/DreamhouseTests.cls
@IsTest
public class DreamhouseTests {
    
    static testmethod void testController() {
        DreamHouseSampleDataController.deleteAll();
        System.assertEquals(0, [select count() from favorite__c]);
        System.assertEquals(0, [select count() from favorite__c]);
        System.assertEquals(0, [select count() from property__c]);
        System.assertEquals(0, [select count() from broker__c]);
        System.assertEquals(0, [select count() from LeadAssociation__c]);
        System.assertEquals(0, [select count() from Lead WHERE company='Dreamhouse']);
    }
    
    static testmethod void testGetPropertiesApexController() {
        Property__c p1 = new Property__c(Name='Prop 1', Beds__c=2, Baths__c=2, Price__c=1000);
        Property__c p2 = new Property__c(Name='Prop 2', Beds__c=2, Baths__c=2, Price__c=2000);
        insert p1;
        insert p2;
        
        PageReference pref = Page.Similar_Properties;
        pref.getParameters().put('id',p1.id);
        Test.setCurrentPage(pref);
        
        ApexPages.StandardController con = new ApexPages.StandardController(p1);
        GetPropertiesApexController ext = new GetPropertiesApexController(con);
        System.assertEquals(1, ext.getProperties().size());
    }
    
    static testmethod void testGetSimilarProperties() {
        Id recordId = 'a0341000002670mAAA';
        String searchCriteria = 'Price';
        Decimal beds = 3;
        Decimal price = 500000;
        Decimal priceRange = 100000;
        MyPropertyController.getSimilarProperties(recordId, searchCriteria, beds, price, priceRange);
        
        recordId = 'a0341000002670mAAA';
        searchCriteria = 'Bedrooms';
        beds = 4;
        price = 600000;
        priceRange = 50000;
        MyPropertyController.getSimilarProperties(recordId, searchCriteria, beds, price, priceRange);
    }
    
    static testmethod void testDreamhouseProspects() {
        Lead l = new Lead(LastName='the Bear', Company='Dreamhouse');
        insert l;
        DreamhouseProspects dhp = new DreamhouseProspects();
        System.assertEquals(1, dhp.getLeads().size());
        dhp.sortList();
        dhp.sortOrder = 'LastName';
        System.assertEquals(1, dhp.getLeads().size());
        //List<Lead> leads = dhp.getLeads();
        
        
    }
    
    static testmethod void testPickListController() {
        String objObject = 'Property__c';
        String fld = 'Status__c';
        PickListController.getPickListValuesIntoList(objObject, fld);
    }

}